theme: rouge-github
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
title: Gheorghi Guzun
description: Assistant Professor of Computer Engineering
institution: San Jose State University
office: ENG 283E
email: gheorghi.guzun@sjsu.edu
