theme: jekyll-theme-slate
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
title: David Chiu
description: Professor of Computer Science
institution: University of Puget Sound
office: Thompson Hall 303
email: dchiu@pugetsound.edu
